### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Rik44444** [te-online/timemanager#10]
thanks for developing this, v useful for us. 
Is there an export/import function (to .ods spreadsheet)>?

**Comment by te-online** [comment]
Hey @Rik44444, unfortunately, there's no export. Feel free to create a Pull Request, though 😉

**Comment by Rik44444** [comment]
too bad:). How are the data stored in NC, would we be able to extract the data from the files directly? I cannot code unfortunately, but i applaud open source software development :)

**Comment by te-online** [comment]
It's in MySql actually, take a look at the data on your own Nextcloud instance :-) Maybe it will be useful for you.

**Comment by Rik44444** [comment]
thanks for the suggestion, i will do that. Can you tell me how I can access the MySQL tables in NC? And if it is in MySQL, then it is by definition exportable/importable right, as long as we can read and edit the MySQL tables?

**Comment by te-online** [comment]
Have a look at your `config/config.php`. You should see your database credentials. How to reach your database pretty much depends on how you or your administrator has setup Nextcloud upon installation. Hope this helps :-)

**Comment by MarcusMerkel-sys** [comment]
I would like to take up the topic: to be able to work with the tool, the export possibility is essential for us. I'm new to github and not familiar with the pull requests - but if someone could take care of the export function on the app, that would be great!

**Comment by te-online** [comment]
@MarcusMerkel-sys Can I use the opportunity to ask you about your use case? 

1. Would you like to export all data or just a single task/project/customer? 
2. Would you like to export as CSV?

**Comment by joleaf** [comment]
A basic export functionality (CSV) is implemented now for the next Andorid version.
You can export all entries, or just for a client, project or task. Then, the created CSV file can be "shared".

**Comment by Ogolar** [comment]
Real great. Thank´s a lot!

**Comment by te-online** [comment]
Please check out [version 0.2.0](https://github.com/te-online/timemanager/releases/tag/v0.2.0) for a reporting feature that addresses this feature request ✨
