### ISSUE TITLE
Entry data is not displayed due to a project selection malfunction

### ISSUE THREAD

**Issue by larsik78** [te-online/timemanager#104]
I can't entry dates because choosing a project or task doesn't work even it is shown in the pulldown menu. 

NC 25.01

**Comment by te-online** [comment]
Hey 👋  Would you mind posting a screenshot of what you see when you can't select a task in the dropdown?

If I remember correctly, I developed this feature in NC25, so it should work. But maybe something broke since then. Let me know if that's possible for you.

**Comment by larsik78** [comment]
![screenshotTimeManager](https://user-images.githubusercontent.com/17160757/206231381-f52094c1-a2de-4100-a307-9f2df663f75e.jpg)

i can't select anything in this dropdown menu.

**Comment by te-online** [comment]
Thanks! I believe you're running into the same problem as #91. Time entries are connected to tasks. As long as you haven't created a task, unfortunately, you can't create a time entry.

I'm closing this in favor of #89, that should fix this UX issue.

Hope this helps.
