### ISSUE TITLE
[Feature Wish] Add Entries to Project without needing a task or a Deck-integration

### ISSUE THREAD

**Issue by aSoftwareByDesignRepository** [te-online/timemanager#106]
Hi Thomas, first of all - thank you for your really good work. I like the idea and the concept of the time manager. I was a bit confused when i tried to enter times in the TimeManager. In German it currently says 'Kunde, Projekt oder Aufgabe' (Customer, Project or Task) when i want to add a new time entry. However i can only add times to tasks. That is a bit confusing since i'm looking for a time-tracking tool that we could use to track time for certain projects but not necessarily on a task basis. That beeing said (or written): As a manager, i want to be able to track time beeing spend on a project without having to create a task within that project (or to have a quick-add feature to add a task when entering the times). 

That would be really helpful - another Feature would be a Deck- or Task integration for Nextcloud since we use Deck to manage our workload within projects.

Thanks again & a very successful 2023,
Alex

**Comment by te-online** [comment]
Hi Alex 👋 Thanks for your kind words and the feature ideas!

I can see how the label might be misleading. Might change it in the next release 😊 

However, I don't have concrete plans for time entries added to projects, or the integrations you mention. Sorry if this isn't what you were hoping for.

Have a good new year!

**Comment by privatemaker** [comment]
> i'm looking for a time-tracking tool that we could use to track time for certain projects but not necessarily on a task basis. 

I also initially needed this level of abstraction, so I created a generic task called `Misc`. However, having task level granularity is needed on some projects.

Perhaps reducing this UX friction/barrier could be achieved auto-generated task `General` or something like I did?

But yah, thanks for the great work making this @te-online 😁

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
