### ISSUE TITLE
Print Report failure with latest NextCloud release

### ISSUE THREAD

**Issue by athanas** [te-online/timemanager#109]
When you attempt to print a report in the REPORTS tab, it will only generate one page (the first page) of the report.  The DETAILS start to print on the first page, but do not carry forward to subsequent pages.

**Comment by te-online** [comment]
I have a suspicion this is because of the new NC25 fixed layout with all its scroll hacks :-(
Are you running Nextcloud 25?

**Comment by athanas** [comment]
Yes indeed, 25.0.3 to be exact.

TimeManager is GREAT!  Thank you all for creating it.

**Comment by te-online** [comment]
Should be fixed in 0.3.5 – let me know if it works again 😊

**Comment by athanas** [comment]
Your fix works perfectly! Thank you so much.
