### ISSUE TITLE
Enhancement: Duplicate time entries

### ISSUE THREAD

**Issue by gbertolottiKS** [te-online/timemanager#111]
Hi.
Firstly, kudos for your work! In my small company, years ago, we made a similar app to keep track internally of the activities done by anyone.
But it was a joy to discover that exist a similar one into the Nextcloud world.

One thing we are missing from our app is the ability to conveniently duplicate a task: selecting a task already done, and selecting "duplicate" created a new task, with the same information, except for the date (by default today's date is put in). In the same flow there was an option to specify for which and how many days to duplicate.
This made it possible to massively create many of the same activities quickly: a classic example is a person working for 5 days on the same thing. One creates a one-day, 8-hour activity and then duplicates it for the other 4 days.

Thanks in advance.

p.s: I cannot promise anything, but I would be curious and willing possibly to develop this functionality myself. Unfortunately, I have never developed anything for Nextcloud, so if there was an opportunity to know where to start and how to take the first steps it would obviously be all smoother.

**Comment by te-online** [comment]
Nice enhancement 👍 

I don't have too much time for anything else than urgent bugfixes and general maintenance, but maybe it will land at some point.

You're welcome to start looking into the code – you can probably get away with adding some javascript that does the duplication – look into the .svelte files ...

Once you have a development setup (you can use the docker-compose file from this repository, by the way, or the [official guide -> click on "Tutorial: How to set up a development environment"](https://nextcloud.com/developer/)), you can follow the guide in the Readme of this repository to transpile the javascript for development.

Let me know if you have questions!

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
