### ISSUE TITLE
3.5.0 lets AIO instance run into "Update needed" screen

### ISSUE THREAD

**Issue by Fred-DTV** [te-online/timemanager#113]
Hey hey,

Our AIO instance has stopped working as of last night when the 3.5.0 update released and ran into this problem https://github.com/nextcloud/all-in-one/discussions/1787

after running the manual occ upgrade command timemanager was the app which needed updating so I am assuming it was the cause.

Unfortunately I have no idea what to do with this information I just felt I should maybe report.

Hope this helps.

**Comment by te-online** [comment]
Hey @Fred-DTV – I'm sorry this happened when you updated TimeManager.

Have you done a manual update of the app via the UI?

I've only ever seen this "Update required" screen when I update the files of an app without using Nextcloud's UI or occ command for that. 

Is there a chance you have some cronjob running or similar that simply pulls new apps into the `custom_apps` folder (assuming you're using the docker image)?

Or maybe you're not persisting the apps folder, so whenever you restart your instance apps are replaced with the latest version, which would also trigger this screen.

For now I can't see anything that points to this being an issue with this app, so I'm going to close this issue. Feel free to re-open if you have new information 😊

**Comment by Fred-DTV** [comment]
hi @te-online 
I think the nextcloud AIO instance manually updates every app that is considered safe to update for the current version. So it probably treid to update it and failed, as it finally did update with the occ upgrade command.

I don't have any cron jobs and yes I am using the AIO docker image on my Synology NAS.

**Comment by Fred-DTV** [comment]
Well looks like we're good soon :) anyways thanks to you for the great app!
