### ISSUE TITLE
Timeinput broken after update to 0.3.5 (chrome)

### ISSUE THREAD

**Issue by pkobert** [te-online/timemanager#114]
**Issue**: The detailed time input popup should not disappear when i release the primary mouse button.

Hey,
i just updated the app to 0.3.5.
It's nice, that the time input field got upgraded. But it's not usable in chrome. When i click the input field the detailed date input popup is only rendered as long as the mouse button is hold down.

I can enter data by holding the mouse button and using the 'Tab-Key' to navigate through the inputs.

![image](https://user-images.githubusercontent.com/86827950/223066503-85031641-e27d-4766-8be4-2313ff6c6835.png)

It's **not** working in chrome 110.0.5481.177 on ubuntu.
It working in Firefox 110.0.1 on ubuntu.

**Comment by te-online** [comment]
Hey 🙂  I'm sorry this is not working for you.

Thanks for reporting, I can reproduce it and will fix it as soon as possible 🙏

**Comment by te-online** [comment]
I just released a new version `0.3.6` that should fix the issue. Thanks again for reporting, I'm clearly not testing in Chrome enough 🤪
