### ISSUE TITLE
Date picker (calender) broken after update to 0.3.6 (chrome)

### ISSUE THREAD

**Issue by ali72r** [te-online/timemanager#115]
Date picker (calender) broken after update to 0.3.6 (chrome)

**Comment by te-online** [comment]
Hey @ali72r Thanks for reporting 👍 

I will fix it in an upcoming release! It appears that click events are prevented and that's why the browser doesn't show the calendar...

**Comment by te-online** [comment]
Should be fixed in 0.3.7 Beta
