### ISSUE TITLE
[Feature Request] Daily/Weekly Target

### ISSUE THREAD

**Issue by benjamindahl** [te-online/timemanager#116]
Would be great to define a daily or weekly target per user to track over- and undertimes.

Cheers
Benny

**Comment by te-online** [comment]
Hey Benny 👋  Thanks for your feature request – sounds like a neat feature. However, it's currently not planned and I'd need to rely on a PR from you or other volunteers to get it implemented 😊

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
