### ISSUE TITLE
sharing clients in android app

### ISSUE THREAD

**Issue by ali72r** [te-online/timemanager#119]
android app (21.12.0) doesn't show clients (projects and tasks) that shared by others.

**Comment by te-online** [comment]
Hey there 👋 Thanks for reporting!

Did this happen before you installed version 0.3.7 of the Nextcloud app? Which version of the Nextcloud app are you running currently?

I have a feeling that this never may have worked, but just want to make sure it didn't get disabled by some recent changes.

Appreciate any further info you can add (Nextcloud version, Nextcloud app version, server OS, SQL database type etc.)

**Comment by ali72r** [comment]
> 

Hey, thanks for your response.
I'm a new user of TimeManager app and I'm testing my needed scenarios.
However, I ensure this issue has been from the 0.3.5 version (the first version that I had).
My current TimeManager app version is 0.3.7 and my current Nextcloud version is 25.0.4.

**Comment by te-online** [comment]
If I understood @joleaf correctly, the Android app is no longer his priority and, yes, I assume sharing support was never available via the sync API 😞 

I'm sorry if this is not the solution you were looking for, but it's the current status and I don't have the resources right now to change anything about that.
