### ISSUE TITLE
Translating 

### ISSUE THREAD

**Issue by Thovi98** [te-online/timemanager#12]
Hello @te-online 

I’m not a developer but I can translate your app ! I never understood how to translate using PR, but I’ve translated fiew apps using Transifex or Weblate. Would you find it usefull ?

Thanks again :)

**Comment by te-online** [comment]
Yes! Thanks for thinking of this :-) You can translate by
- Cloning the repository into your own Github account
- Create 2 new files in the `l10n/` folder, named like this `[language_shorthand].json` and `[language_shorthand].js`
- Now copy the contents from another language and replace all strings on the non-English side with your own translation
- When you're done and you have comitted your changes, you create a Pull Request on *this* repository and Github will automatically suggest that you create a Pull Request from your fork that you edited before

Hope it makes sense :-)

**Comment by Thovi98** [comment]
Okay thanks for this explanation ! I’ll try to translate when I find some time 😃

**Comment by Thovi98** [comment]
Thanks for the update !
But translation works only for a part. See screenshot : some words are translated, some are not.
![2020-11-30 16_23_09-](https://user-images.githubusercontent.com/51749973/100628364-6ddf6f00-3328-11eb-9b86-b06c10e0d9dc.jpg)

When I go to the Logging setting, I see this warning repeatidly : 

```
[l10n] Warning: Failed to load /var/www/nextcloud/apps/timemanager/l10n/fr.json - json error code: 4

GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json
from [ipv6] by thomas at 2020-11-30T15:24:29+00:00
```

Maybe I made a syntax mistake while translating `fr.json` file ?

**Comment by Thovi98** [comment]
Okay I’ve found the syntax error, I will make a PR.
