### ISSUE TITLE
Losing Allowed Users on Project on Color Change

### ISSUE THREAD

**Issue by hdzierz** [te-online/timemanager#123]
Hi There,

When changing the color of an existing project using the edit project dialog,  I am losing the "allowed user" on that project. This prevents the user from selecting that project for tracking time.

Version: 0.0.79

Cheers

H

**Comment by te-online** [comment]
Hey there 👋  I think you may be using a different Nextcloud app? This app doesn't have colors or allowed users and therefore probably doesn't have this bug 😊
