### ISSUE TITLE
Date and Time is not localized correctly?

### ISSUE THREAD

**Issue by reox** [te-online/timemanager#125]
I'm testing out this app now but noticed that even though the interface is in German, the time is in 12h format and the date is in mm/dd/yyyy - but only in the date picker.
Ideally, I would like to see 24h format and dd.mm.yyyy
![image](https://github.com/te-online/timemanager/assets/431045/62a5c979-c34f-4ca5-bce7-ac27e21407a2)

Is there a setting I'm overlooking?
For example, in deck everything is correct: 
![image](https://github.com/te-online/timemanager/assets/431045/be35b7be-6c00-47c7-816c-63f60a22a264)

**Comment by te-online** [comment]
Hey there 👋 Thanks for reporting.

I use native HTML input fields, and the localization is applied based on your browser preferences. Try changing the settings in your browser and input fields should adjust accordingly.

I'm sorry if this is not what you'd expect, but it's how it works currently :-/

Here's an example in Firefox:

![Screenshot 2023-05-13 at 20 42 00](https://github.com/te-online/timemanager/assets/4127167/da004387-6224-4a0b-b065-7c46a4e5c130)

![Screenshot 2023-05-13 at 20 42 38](https://github.com/te-online/timemanager/assets/4127167/b83fea27-e945-47a0-8a4e-5792ebfe8f80)

![Screenshot 2023-05-13 at 20 42 53](https://github.com/te-online/timemanager/assets/4127167/e13db959-44ba-40a4-afab-503c23652f3c)
![Screenshot 2023-05-13 at 20 42 20](https://github.com/te-online/timemanager/assets/4127167/2003abd7-6b6c-4e8e-901b-e4ebbd8df680)

**Comment by reox** [comment]
thanks for the explanation, I understand ... but I don't understand :D
Yes, the browser is set to English US, but this is the first time I notice this problem... I thought that Firefox would also adjust to the operating system settings, but maybe it does only on certain instances? idk... But good to know that the language settings can have such an impact!
