### ISSUE TITLE
Android app: Shared items not appearing

### ISSUE THREAD

**Issue by vanyolai** [te-online/timemanager#126]
Shared items are not appearing, can't use shared clients, tasks, etc. If I share them, it appears to be shared, but not appearing on the other side's app/phone client.

**Comment by te-online** [comment]
Yes, this is a known limitation of the current API. Furthermore, the maintainer of the Android app does not use it anymore and is therefore unlikely to add support for it, even after I update the API. 😢 

We can only hope that someone will develop a new app or making an app will be in scope for me at some point. Sorry for the bad news...

**Comment by te-online** [comment]
You can open an issue here: https://gitlab.com/joleaf/nc-timemanager-mobile-app
