### ISSUE TITLE
Add PSP/WSB elements

### ISSUE THREAD

**Issue by Lukas2112** [te-online/timemanager#127]
The idea behind this feature request is that a so-called work breakdown structure (WBS) element can be stored for each project and each task.

**Comment by te-online** [comment]
Please see my response here https://github.com/te-online/timemanager/issues/128#issuecomment-1584886782

Again, hoping for your understanding that this is not something I will be looking into.

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
