### ISSUE TITLE
Approval process from registered effort

### ISSUE THREAD

**Issue by Lukas2112** [te-online/timemanager#128]
The idea behind this featuring quest is that for each project and task a responsible person can be defined.

If now collaborators from another team book corresponding effort, then this can be approved or rejected by the respective project or task responsible.

**Comment by te-online** [comment]
Hey @Lukas2112 

Thanks a lot for your feature request. I will leave it open, so people can pick it up. 
However, just to manage expectations, it will be _very_ unlikely that I will implement this myself.

My vision for this Nextcloud app is that it should provide basic time tracking to get you started. What you describe is a complicated workflow, which in my opinion would be a better fit for an app target towards a different audience.

Hope you understand 😊

**Comment by te-online** [comment]
I'm not sure, it may be. Haven't used the approval process you mention. Is there any documentation you can link me to? 😊

**Comment by te-online** [comment]
Thanks 👍

It looks to me like it's applied to files and implemented within the files app, so I don't see any direct path to include this feature into this app. But it's good to refer to something for inspiration, should this be picked up at some point 😊

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
