### ISSUE TITLE
Employee time clock (Track Employee Hours)

### ISSUE THREAD

**Issue by moosavisa** [te-online/timemanager#131]
Dear developers

I had a suggestion for a new feature in the app. 

In some countries SME or either startups ought to track employees working hours. How much time day attend work or how much time off the work.
To comply with these tracking hour regulations some startups or SMEs use mobile or web-based apps. They collect data from staff and can manage wage and payments. Also the company need to export and save these data to meet regulations.

Here I suggest:
"A clock for work" section in Nextcloud, where employees can clock-in and out using either a web or a mobile app.
Timesheets be created automatically, making payroll processing faster and more accurate.
Not only this, but the clock for work let to manage absences, overtime, have an overview of real-time presence in the team (company), and if possible have some basic options for HR analytics.
Just a simple drawing:
![249706754-7941f162-74f7-48a6-b684-f41987e87ba2](https://github.com/te-online/timemanager/assets/105066435/9593a69c-c01a-48b0-848c-1cb2dead23cc)
![249706766-565523b9-762c-442f-92f1-e4ad52ab9d8b](https://github.com/te-online/timemanager/assets/105066435/4ea3ec1d-f209-4908-83eb-0472ce039b57)

**Comment by te-online** [comment]
Hey there 👋 

Thanks for opening an issue. This looks to me like a brilliant idea for a new app.

Since I don't need this feature, I'm currently not interested in adding it. My vision for this app is to keep it as simple as possible.

That being said, I do have plans to add a often asked for "recording" feature #11

**Comment by MrLoverLoverMMMM** [comment]
I would also like to be able to monitor employee time inclusive automatic lunch break time subsctraction.

**Comment by kaffeeringe** [comment]
Clocking in and out is also nice for tracking time on projects while you work on them. We use toggl.com at the moment. And they also have this play-button-function. You press the button, choose the customer/project/task and it counts the seconds until you either switch tasks or press stop.

So even if you don't want to track working hours (which is mandatory in all EU countries) the UI-idea is nice.

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
