### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [te-online/timemanager#134]
- It would be nice if you could setup that after a specific amount of hours / day it remove a certain lunchbreak (e.g.: 20 min.) automatically.

- Day Pool: It would be nice if you can choose unlimeted or limited amount of days / project or task. That would mean I for instance have max. 10 days for an project and when they are used up I get a warning or something.

**Comment by te-online** [comment]
Hey there 👋 

It looks like there are some similar feature requests here:
- https://github.com/te-online/timemanager/issues/116
- https://github.com/te-online/timemanager/issues/80

I'd close this one in favor of the other, existing issues 😊 

That being said, there's currently no-one working on these features as they are quite nice (in my view) and not something I'm looking for in this app. If you'd like to add them, you're welcome to open a PR and discuss a proposal here on Github or fork this app and make your own version.
