### ISSUE TITLE
Timemanager stores the wrong time in database

### ISSUE THREAD

**Issue by sunstep** [te-online/timemanager#135]
When I add a new entry:
![image](https://github.com/te-online/timemanager/assets/73174517/beeb4ee0-0310-4115-89b3-02cfe79bdeda)

It will store the time wrong in the database:
![Untitled](https://github.com/te-online/timemanager/assets/73174517/a7cfbf70-4d2d-4bb5-aa42-3597e630281b)

If we look at entry number 21, we can see that the time differs from what I entered in the first image. This will cause the entry to show the wrong time in the mobile app:

![image](https://github.com/te-online/timemanager/assets/73174517/c4f3eb90-2dc7-4128-98ed-d430450710bd)

I added a custom note, so we can confirm that it actually stores the time wrong. This seems like an issue outside my control, can anyone look into this?

**Comment by devattendant** [comment]
Assuming you are based somewhere in Central Europe (Germany, etc.) in a country which currently is in CEST (UTC+2) timezone, the times in Timemanager as well as in the database are correct. Timemanager displays and handles dates and times based on your system/browser timezone (or from NC Calendar, not sure right now). However, the data is saved as UTC in the database.

So 15:59 CEST (UTC+2) = 13:39 UTC.

I contributed this "complexity" to the plugin in late 2022 to be able to track times accordingly when working from different timezones/countries. However it seems that the Nextcloud Timemanager app has been last updated on 26.12.2021 in Google Play so it may not adopt the timezone to your local time and there displays the UTC times.

**Comment by sunstep** [comment]
I see, in that case it's probably the mobile app being outdated indeed. Thanks for clarifying this. Though, can anyone actually tell me if there are plans for updating the mobile app to support this, so it doesn't show the wrong times?

**Comment by te-online** [comment]
Yes, it seems to me like @joleaf doesn't use the app anymore and therefore has stopped development 😬 

I'm sorry about the situation, but not much I can do about it right now.
