### ISSUE TITLE
Cannot see time-entries on shared clients

### ISSUE THREAD

**Issue by stvogel** [te-online/timemanager#139]
As I see feature #65 is implemented and that's a great feature.
But maybe I'm misunderstanding the use of it.

I have user "coworker" and user "manager". user "coworker" creates a client "client1" and shares it with "manager".
Now I assumed that all time-entries created by "coworker" should be visible to "manager".
But "manager" only sees the shared client "client1" and working hours is always 0.

I hope this is just a bug. Else I completely misunderstood the usage of this feature.
(I am looking at this in the web-app - not the android-app).

**Comment by te-online** [comment]
Hey @stvogel 

Try the other way around 😊 Your manager should create the clients for your coworker and share them with the coworker.

As you can see from the copytext in the sharing modal, it is only the owner of the client who can see all time entries. Other people will only see their own time entries.

<img width="542" alt="image" src="https://github.com/te-online/timemanager/assets/4127167/f1b5dbef-0060-4055-a61f-87ff6f405dc7">

I'm sorry if this is not the solution you'd prefer, but this is how it works currently 🤓

**Comment by stvogel** [comment]
Ahhh. That's exactly what I want. Nice. Makes sense.
Thanks a lot.
