### ISSUE TITLE
Browser tab icon

### ISSUE THREAD

**Issue by Thovi98** [te-online/timemanager#14]
Hey @te-online 

Last issue for now, I promise 😆 
I’ve noticed that your app does not have an icon on the browser tab, it shows like this : 
![2020-10-06 12_58_05-Microsoft PowerPoint - DroitdessÃ»retÃ©s_2020_Cours1 pptx  Enregistrement automa](https://user-images.githubusercontent.com/51749973/95193239-c89a9580-07d3-11eb-8f64-9052febecae1.jpg)
The icon is only blue, but doesn’t show your little logo clock.

Thanks again 🥇

**Comment by te-online** [comment]
Hm... I've never thought about this. Didn't know that you can customize the favorite-icon per app. I thought it was set per Nextcloud installation? Within your theming app? If you can find some documentation or examples of how this works on a per-app basis, please feel free to share it here :-)

**Comment by Thovi98** [comment]
Oh I don’t know... It’s only what I see from my user experience, but I will do some research when I find some times to, hope to be able to help you !

**Comment by te-online** [comment]
Were you able to find any further information about custom favorite icons per app? @Thovi98

**Comment by Thovi98** [comment]
Unfortunately I’ve not find anything. I’ve searched a bit in the Nextcloud documentation, but I’m not a developer so it’s not easy.

Maps app has the same issue, but nobody answered yet (https://github.com/nextcloud/maps/issues/533#issue-797669706).

**Comment by te-online** [comment]
Hey @Thovi98 I just made a small change, replacing navigationmanager with some config in `info.xml`. I have a hunch that maybe this could fix your favicon situation. It's not merged and released, yet. 

Would it be possible for you to test the feature branch? https://github.com/te-online/timemanager/tree/feature/replace-navigation-manager 🤓 

I can't really test this, and I believe this is because I don't have a single Nextcloud instance where ImageMagic is built so it can handle SVGs, which is apparently required for favicon related features.

**Comment by Thovi98** [comment]
Hello @te-online !
Thanks for the update. I’m currently doing my exams, so I don’t have so much time to test... I will try as soon as possible, but I don’t think I will be able to test this mount :’( 

Thanks.

**Comment by te-online** [comment]
Hey @Thovi98  – no worries. I'll add it to the next release (in a few weeks time) as it does not seem to break anything. Then you can simply test by updating your current version of the app. All the best for your exams :-)

**Comment by te-online** [comment]
Please check out [version 0.2.0](https://github.com/te-online/timemanager/releases/tag/v0.2.0). There is a very slight chance that now the icon is custom 🤷

**Comment by Thovi98** [comment]
Sorry for the late reply ! The icon is unfortunately still empty... :’(

**Comment by te-online** [comment]
@Thovi98 Thanks for checking – the never ending journey 😂 I will let you know if I discover any other approaches
