### ISSUE TITLE
Impossible to change TAKS from Time Entry ?

### ISSUE THREAD

**Issue by Maromax74** [te-online/timemanager#145]
Is it impossible to change TASK after Time Entry operation ? Sometime this may be very helpful.

![Screenshot_20231023_151919](https://github.com/te-online/timemanager/assets/80688690/0580f385-1132-4558-98f9-7c9e99f255cb)

**Comment by te-online** [comment]
Hey 👋 Thanks for your question. Yes, this is by design 😊 

There's a feature request here, please subscribe to this issue to follow future progress on that: https://github.com/te-online/timemanager/issues/61
