### ISSUE TITLE
Recurring tasks

### ISSUE THREAD

**Issue by nemoBE** [te-online/timemanager#146]
Thanks for the great tool.

It would be helpful to add an option for recurring tasks.
Best

**Comment by te-online** [comment]
Hey @nemoBE Thanks for your suggestion 😊 It's unfortunately not something I currently plan to add, just to manage your expectations. But who knows what the future will bring!

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
