### ISSUE TITLE
not loaded timemanager after update to 0.3.10

### ISSUE THREAD

**Issue by ali72r** [te-online/timemanager#149]
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

**Comment by ali72r** [comment]
روی نسخه ی ۳.۹ هم خطای زیر رو داریم:

{"reqId":"U8gra2V47XilLcrr0PJK","level":3,"time":"2023-12-12T14:06:05+00:00","remoteAddr":"5.144.128.33","user":"admin","app":"index","method":"GET","url":"/index.php/apps/timemanager/","message":"syntax error, unexpected ')', expecting variable (T_VARIABLE)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"25.0.7.1","exception":{"Exception":"ParseError","Message":"syntax error, unexpected ')', expecting variable (T_VARIABLE)","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"function":"spl_autoload_call"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"__construct","class":"ReflectionClass","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":134,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":466,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":438,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":159,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1048,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/timemanager/lib/Controller/PageController.php","Line":91,"CustomMessage":"--"}}

**Comment by te-online** [comment]
Hey 👋 

I haven't done any changes to `PageController.php`, so it seems to me that maybe your app installation did not complete. After **backing up your Nextcloud database (!)**, try if you can uninstall and re-install the app.

Or maybe you just need to wait for the OPCache to be cleared?

Let me know if that helps.

**Comment by ali72r** [comment]
> Hey 👋
> 
> I haven't done any changes to `PageController.php`, so it seems to me that maybe your app installation did not complete. After **backing up your Nextcloud database (!)**, try if you can uninstall and re-install the app.
> 
> Or maybe you just need to wait for the OPCache to be cleared?
> 
> Let me know if that helps.


We have reinstalled the app many times. Even tried version 3.9 with manual installation. None of them fixed the issue. Also we have this problem for many days now. I don't believe it can be caused by OPCache.

The error specifically shows "syntax error, unexpected ')', expecting variable (T_VARIABLE)" it seems like something is incompatible or a coding issue for NextCloud v25

**Comment by te-online** [comment]
As you can see, there's nothing suspicious in line 91 in `PageController.php`:

https://github.com/te-online/timemanager/blob/main/lib/Controller/PageController.php#L91

The bracket closes the __construct() parameters list.

Can you have a look at your version of the file and see if it looks the same?

**Comment by te-online** [comment]
@ali72r Maybe it's the trailing comma that is the issue here?

https://wiki.php.net/rfc/trailing-comma-function-calls

Do you run PHP < 7.3 by any chance? I don't think this app supports that. You should update to PHP >= 8.1 as PHP 7.x is EOL and won't receive security updates.

**Comment by ali72r** [comment]
> Hey again 👋
> 
> I reproduced your error. It is indeed the trailing comma that is the problem. Which is strange, because it should have been implemented in 7.3 according to the PHP Wiki...
> 
> Regardless, I'm a little hesitant to push _another_ update after I already had to push out a hotfix, as this only affects old PHP versions.
> 
> Would you be able to fix this yourself?
> 
> You need to change:
> 
> * `/lib/Controller/PageController.php:90` -> remove the comma at the end
> * `/lib/Controller/TApiController.php:66` -> remove the comma at the end
> 
> Another option is to upgrade to at least PHP 8.1, which I recommend. Let me know how it goes.

Thanks for guiding us. The bug has been fixed after upgrading PHP to 8.1.

> Hey again 👋
> 
> I reproduced your error. It is indeed the trailing comma that is the problem. Which is strange, because it should have been implemented in 7.3 according to the PHP Wiki...
> 
> Regardless, I'm a little hesitant to push _another_ update after I already had to push out a hotfix, as this only affects old PHP versions.
> 
> Would you be able to fix this yourself?
> 
> You need to change:
> 
> * `/lib/Controller/PageController.php:90` -> remove the comma at the end
> * `/lib/Controller/TApiController.php:66` -> remove the comma at the end
> 
> Another option is to upgrade to at least PHP 8.1, which I recommend. Let me know how it goes.

Thanks for guiding us. The bug has been fixed after upgrading PHP to 8.1.

**Comment by ali72r** [comment]
> Hey again 👋
> 
> I reproduced your error. It is indeed the trailing comma that is the problem. Which is strange, because it should have been implemented in 7.3 according to the PHP Wiki...
> 
> Regardless, I'm a little hesitant to push _another_ update after I already had to push out a hotfix, as this only affects old PHP versions.
> 
> Would you be able to fix this yourself?
> 
> You need to change:
> 
> * `/lib/Controller/PageController.php:90` -> remove the comma at the end
> * `/lib/Controller/TApiController.php:66` -> remove the comma at the end
> 
> Another option is to upgrade to at least PHP 8.1, which I recommend. Let me know how it goes.

Thanks for guiding us. The bug has been fixed after upgrading PHP to 8.1.

**Comment by te-online** [comment]
Great you fixed it by upgrading 🙌 

I have (unofficially) restored PHP 7 support in the latest version 0.3.11, by removing the trailing commas. No guarantees that it won't come back, though 😊
