### ISSUE TITLE
Possibility to change time formats

### ISSUE THREAD

**Issue by Oberlurch3000** [te-online/timemanager#151]
Hello,

I would prefere to show my time entries in hh:mm format. Since our business records times in this formal it would be helpful not having to calculate what 1,37 hours are in hours and minutes. It could be a nice to have feature ;).

**Comment by te-online** [comment]
Yes, that's a valid request 😊 Personally, I only work with decimal type hours, but some people have requested what you mention.

However, I'm closing this as duplicate of the existing issue. #18
