### ISSUE TITLE
Once a client is shared with a group the author is a member of, it can't be edited

### ISSUE THREAD

**Issue by nicolas-75** [te-online/timemanager#152]
I installed version 0.3.11 and shared a client. Unfortunately, once this is done it is impossible to update the share (add another person or group, as well as delete the share).

I don't know if this is the expected behavior, but I don't find it practical, so I'd rather report a potential anomaly.

**Comment by te-online** [comment]
Hey – that doesn't sound like intended behavior. Can you talk a little bit about your setup? Nextcloud version, database (MariaDB vs. MySQL), PHP version. I will try to reproduce this bug then and provide a fix 😊

**Comment by nicolas-75** [comment]
The Nextcloud version is 26.0.9

The database is Version : PostgreSQL 13.12

The PHP version : 8.0.30

I use an instance from https://cloud68.co/ If you want one for some tests, I can ask a new one, then I will send you credentials.

**Comment by te-online** [comment]
Thanks, I will check it out 😊 Give me a few days! Sorry for the issues...

**Comment by te-online** [comment]
Short update: This could be a Postgres issue, similar to #150.

I have yet to get my development environment to work with Postgres, then I can reproduce and fix the issue. Apologies.

**Comment by te-online** [comment]
Hello @nicolas-75, Sorry about the delay.

Do you have access to `[your-cloud-domain]/settings/admin/logging`?

I finally got a development setup with Postgres to work, but I can't reproduce your error. Maybe it's something specific about your setup or your data? We need to take a closer look a the logs to find out.

If you don't have access to the logs, we need to figure out a different solution. I need to be able to reproduce the error before I can fix it, unfortunately 😞 

Did you ever have any versions before or was 0.3.11 the first version you ever installed?

**Comment by nicolas-75** [comment]
I use a new instance from https://cloud68.co/ If you want to test, I can subscribe a new instance for some months and give you access.

**Comment by te-online** [comment]
If you'd be wiling to do that, we can try it 🙂 Just shoot me an email, when you have it set up and I will take a look shortly after.

**Comment by kominoshja** [comment]
Hi @te-online

Boris, part of the [Cloud68.co](http://cloud68.co/) team over here,
We found this issue after @nicolas-75 requested an instance for you to test with

Before talking about the in-evitable technical details, we want to take the time for thanking you for your efforts in developing this Nextcloud App. It seems to fit really well into the Nextcloud ecosystem, and we look forward to see it spread more and more

Indeed it could be a postgresql issue, so we think it’s worth having an environment where you can experiment with, in a setup that’s identical to the one we provide for @nicolas-75 and all other subscribers.

We can provide a month-long instance for you with full root access so you can check everything hands on, and you can also use our support system to further discuss things. I hope that this helps in solving this issue, and it has a positive impact on the usage of this app

**Comment by te-online** [comment]
Thank you @kominoshja – great to hear! 😊 

I will reach out to you shortly to take a closer look!

**Comment by dianelou** [comment]
Hello @te-online 
My association is trying to use timemanager on mobile and it seems we have the same data synchronization problem.
We just updated nextcloud with the version 28.0.2.
How can we check which version of timemanager is installed please ? and how can we install the 0.3.11 please ?

Thank you for your help

**Comment by te-online** [comment]
@dianelou If you are using PostgreSQL, the fix for that is unfortunately not released, yet. However, if you are using MySQL or MariaDb, you should be fine on the latest version. You can always check [for the latest version in the Nextcloud App Store](https://apps.nextcloud.com/apps/timemanager) and you can check your currently installed version by going to your Nextcloud, clicking on the user avatar in the right top corner and clicking on "Apps", then looking for the app you'd like to manage.

**Comment by nicolas-75** [comment]
@te-online how can I send you credentials to login in the instance in order to do the tests you want to do?

**Comment by te-online** [comment]
Hey @nicolas-75 You can upload a file to this file-drop here: https://te-cloud.de/s/4ifGKz2SHqyRefd
Would that work?

**Comment by te-online** [comment]
Hey again @nicolas-75 

I just tested your scenario on the test instance and it works flawlessly 😢 

Can you help me try to reproduce your issue? Maybe do a screenrecording, so I can see what's going on?

Maybe you could try it on the test instance, since I can see you have an account there as well. Try sharing a client with me "Thomas" and undo it again.

Let me know how it goes 😊

**Comment by punkyard** [comment]
hi
i've shared a client with a group for the first time (i don't think this was possible before - as I thinked I asked for that functionality some day before ^^)

but after sharing this client with a couple of tasks, I can't do any changes anymore.
I can't remove the share, I can't edit nor the client nor the tasks .. nothing ..
but we can add time entries apparently

I hope this can evolve ^^
It's on brave, AiO 7.12.1, NC 27.1.5

<img width="73" alt="Capture d’écran 2024-02-18 à 15 55 47" src="https://github.com/te-online/timemanager/assets/59349105/015e3d0b-4955-4094-94ae-809f75de7917">

**Comment by te-online** [comment]
Oh! This is a good hint. I will try sharing with a group, maybe that's what broke for OP.

**Comment by te-online** [comment]
I finally reproduced this issue. It seems like a UI issue. 

The edit buttons seems to be hidden by mistake once you've shared a client with a group.

I will report again when I have a fix ready.
