### ISSUE TITLE
REQ: change time in hours to minutes

### ISSUE THREAD

**Issue by punkyard** [te-online/timemanager#153]
<img width="358" alt="Capture d’écran 2024-01-13 à 14 39 14" src="https://github.com/te-online/timemanager/assets/59349105/129ee45e-f760-4324-a0ae-105ac4bffb13">

**Comment by te-online** [comment]
Related to: https://github.com/te-online/timemanager/issues/18

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
