### ISSUE TITLE
error in PDF print

### ISSUE THREAD

**Issue by punkyard** [te-online/timemanager#156]
<img width="680" alt="time manager print" src="https://github.com/te-online/timemanager/assets/59349105/e41489bb-f3c5-48f9-b62e-cb4c6e51d1e2">

when printing a report to PDF
graph is not displayed

thanks for this great app
we are coming to a decision to choose it over Time Tracker
especially for the ability to share clients with co-workers

**Comment by te-online** [comment]
This is unfortunately controlled by the browser's print heuristics.

When I use Firefox, I have these checkboxes at the bottom:

<img width="231" alt="image" src="https://github.com/te-online/timemanager/assets/4127167/c1f774aa-f3e2-452b-be2f-02262b10598c">

Do you have something similar in your browser that could make the bars visible before exporting?

**Comment by punkyard** [comment]
YES indeed! activating the graph option in Brave worked 👍
but not in safari

in Brave, bars are white - could be nice to have a nice blue bar in the PDF as in the app

**Comment by te-online** [comment]
Great it worked 😊 Yeah, I haven't experimented with the print style a whole bunch, but it seems that it's quite difficult to convince browsers to print background colors. It may be an old heuristic to save ink? 

If you have an idea on how to fix it in CSS, you're welcome to suggest it or create a PR 🤓

**Comment by punkyard** [comment]
i'm afraid it won't be of any help in this matter
