### ISSUE TITLE
REQ: assign user to a time entry

### ISSUE THREAD

**Issue by punkyard** [te-online/timemanager#157]
a really great option is to share client with workers! thanks!

But "Created by" in Reports shows "no option" :/

<img width="1048" alt="Capture d’écran 2024-01-16 à 00 14 49" src="https://github.com/te-online/timemanager/assets/59349105/7047b096-4bfc-42c9-97a6-5395844b43a1">

Could it be possible that Admin of the client could edit the user assigned to a time entry?

This was done in Brave, with NC 27.1.5

**Comment by punkyard** [comment]
I hope you find our feedback useful to your valuable work.

**Comment by te-online** [comment]
Hello @punkyard There's no user assigned to a time entry as such, I'm just looking at which user created the entry.

To get suggestions in the "Created by" field on the "Reports" page, start typing. It will search all users in your Nextcloud.

Hope this helps you resolve this. Sorry if it's not the way you wanted it to work!

**Comment by te-online** [comment]
I think what you're looking for doesn't really fit the mental model of app, I'm afraid 😢 

There isn't really an "admin" in this app. Someone can choose to share a client with other people, but that's it. 😊 
Every object is created with an author. In my opinion it doesn't make sense to change the author after the fact. 

Your request could be fulfilled by a new feature where a time entry can be "assigned" to a person. Then it would make sense to change that assignment. But this scenario sounds a lot like a project management tool to me, so maybe you're looking for a different tool here 😊 

Again, sorry if this is not the answer you were hoping, but this doesn't seem like a important thing to add to app right now. I'm trying to keep it lean and mostly stable.

**Comment by punkyard** [comment]
I understand there is no admin in Time Manager - i used it as a general term in 'permissioning'
But there is the owner of a client that would share his client, projects and tasks to co-working users.

As a user of NC which is a collaboration and project management, time management is sometimes tricky, moving, has to be adaptive to match unwanted changes in our work.

I guess the thought of my group of simply changing the creator field of an entry by the owner of the client, comes in a broader thought on editing time entries.

At the moment, if anything moves in our organisation, we need to recreate entries in the right place (move a task in a project, as an example). And then delete the original entries.. that's not flexible for us.
Sometimes we need to be able to edit entries origine, not just the timing.

This is why we are write a suggestion: time entries possibility to be edited: change time, task, projet, client and user!

I guess we understand how important stability is in development, and how stability can be challenged by complexity of the features of the app. Keep it real! Keep it simple! to make it work!

Great job by the way! We've just started testing it, and we would like to share with you the limits we encountered in our daily activities. If our suggestion is misplaced, and our needs can't be heard, let's just dump this thread :)

✌️

**Comment by te-online** [comment]
Okay, got it 😊 

I'm keen on enabling moving any kind of object (time entries, projects, tasks) freely at some point, which makes sense. There's an issue about that actually #61.

Still not convinced about changing the author after the fact 😅 But I'll consider it 😊 

What would be the use case? You deleted a user? Someone enters the time on behalf of someone else? Imagine a time entry like a file in Nextcloud, you can't really change ownership of that one either. Another user can copy it, sure, but not the owner (at least not that I know of...).

**Comment by punkyard** [comment]
@te-online 
let me tell you first how pleasant it is to exchange with you. I rarely feel that much attention in the IT world of devs ..

Now,
"changing the author" might again be the wrong terms I used that gave you this idea.
Said differently, if it's possible to "change" the author, it could mean also it could be possible to "create" an entry for a co-worker. This, for two main reasons:
- the worker doesn't have the time to do it, or just can't
- this way, a team manager could share the time table to his team

Even if this sounds strange to you, I work for non-profits, and volunteers don't always have the time of desire to do that job of entering their activities in a computer - some don't even want to use computers ^^
But here, in France, work of free-workers is valuable to a non-profit. If we can sum it up by volunteer, we give value to our fragile missions and to our annual reports ..

These are the two main reasons we are concerned by, but there is a couple of others that could be listed.

Don't think I want to mess with your app - and so, your time - if I take the time to express a request it's because my team and I have identified a need .. your app could fulfill 👍

Now, let me tell you quickly about my projects: I'm working freely on developing an interface to help non-profits and artists to come back to the usage of modern Internet collaboration softwares, as we can see they can't compete with bigger organisations that possess all the technologies for big commerce.

I'm not an coder, but I've had to gather skills - to be able to be here first of all, chatting with you - and to be able to understand the functioning of the servers that make the Internet and a tiny bit if the languages spoken here ^^

Are you interested? Do you want to know who we are and what we do?
listen! :) https://lataache.org

**Comment by punkyard** [comment]
.. and I believe you can change the ownership of a folder or a file  ☺️

<img width="781" alt="Capture d’écran 2024-01-19 à 22 07 29" src="https://github.com/te-online/timemanager/assets/59349105/a7ce8f80-b79c-47b5-a1c2-89c665ea6b1e">

**Comment by te-online** [comment]
Hm ... I didn't know that one 😅 Thanks for sharing!
