### ISSUE TITLE
Fatal Exception after Nextcloud 28.0.4 upgrade

### ISSUE THREAD

**Issue by thomaskor** [te-online/timemanager#163]
Hi,
after update Nextcloud to 28.0.4 the App doesn't work.
---
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
---
Extract from Log:
"message":"Creation of dynamic property OCA\\Extract\\AppInfo\\Application::$appName is deprecated at /var/www/nextcloud/apps/extract/lib/AppInfo

Thanks
Thomas

**Comment by NeurohrByteS** [comment]
Same error from the logs: Timemanager doesn't work with Nextcloud 28.0.4
```
Timemanager InvalidParameterException Parameter "appName" for route "core.Js.getJs" must match "[^/]++" ("/apps" given) to generate a corresponding URL.Exception thrown: Symfony\Component\Routing\Exception\InvalidParameterException
```

**Comment by te-online** [comment]
Hey! I'm really sorry this is happening, I can reproduce it in my dev setup 😞 

It seems like some part of the lookup for JS files in templates is broken in version 28.0.4 of Nextcloud. I commented on an issue in the Nextcloud/server repository and hope to get an answer soon.

In the meantime, on my dev container I was able to fix the Exception [by doing these changes](https://github.com/te-online/timemanager/commit/6898f88f0b39a649f8d4c3a1072d8a4c2f1715b2) in the templates files.

If you can access and edit the app files on your server, please try if you can fix the issue by applying these changes and report back, if you have the time. 

I still had issues activating the app via the UI, even after the changes, so I used occ. Before releasing a fix, app activation has to be fixed and testing has to be done with older versions of Nextcloud. But if this fix goes in the right direction, I hope to have a new version out to address this early next week.

It seems like Nextcloud's QA testing does not cover all scenarios, especially of apps using older mechanisms (that I cannot find a deprecation notice for, though) and that haven't been rewritten in the past years. 😿 

Thank you for your patience 🙏

**Comment by thomaskor** [comment]
Hello Thomas,
Thanks for the quick response.
The workaround works.
I'll close the ticket.
Have a nice Easter
Thomas
