### ISSUE TITLE
time tracker suddenly disappeared

### ISSUE THREAD

**Issue by dcrobertson01** [te-online/timemanager#165]
Hi. I've been using time manager for a couple of months - mostly with the app on my phone. Today, the time tracker vanished. Finished one task, went to start another task, but could only add either start and end times or a duration. The tracker seems to have gone. 

I've looked at the web app and the tracker isn't there either.

A bit puzzled.

**Comment by te-online** [comment]
Hey, I'm sorry this happened! I have never used the Android app and don't know how the timer works, neither how it's implemented. Maybe your phone is backgrounding the app and it gets terminated? 

Please make sure to ask @joleaf, but keep in mind that the project has been retired a while ago: https://gitlab.com/joleaf/nc-timemanager-mobile-app/-/issues

Sorry that I don't have better news for you 😞
