### ISSUE TITLE
Export report to XLSX

### ISSUE THREAD

**Issue by Kaelber** [te-online/timemanager#168]
Um die exportierten Daten ohne Umformatierungen verwenden zu können, wäre eine Excel-Formatausgabe hilfreich. Gute Lösung z.B. in myHours:

https://app.myhours.com

**Comment by te-online** [comment]
Hm... I've heard before that Excel doesn't open CSV files. Is that right? Can't you just do right click -> "Open with..." or whatever Windows calls this? 😅 

I'm not too flexible on time right now, but I guess it would require pulling in a library that can write Excel binary files and adding a button to invoke that library. So actually quite a good task for someone who wants to contribute ... 😉

**Comment by Kaelber** [comment]
I among other things also tried this, but unfortunately it doesn't work. When I open the CSV, I am directly in the table and cannot do anything with the values. If I save the export as TXT, I can select which font and which separator should be used when opening in Excel. This works so far. Unfortunately, however, the hourly values with a dot are then interpreted differently, so that the values are changed and can no longer be used. If a comma had been used instead of a period, the result would probably not be distorted. All in all, unfortunately, a bit cumbersome and also unusable.

I must say, I use german installations of Excel, so the values are in a different condition as in english spoken countries.

**Comment by te-online** [comment]
So maybe changing the decimal separator based on user locale could fix some of the issues maybe 🤔

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
