### ISSUE TITLE
Markdown for project entries

### ISSUE THREAD

**Issue by c0decave** [te-online/timemanager#17]
Right now, entries seem to be just lines of text without any sort of formatting. Markdown https://www.markdownguide.org/ would be pretty cool.

**Comment by te-online** [comment]
Hey @c0decave Thanks for your feature suggestion. This sounds like a really good idea 👍

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
