### ISSUE TITLE
Group-Share does not work with Active-Directory-Groups (only works with NC-internal groups)

### ISSUE THREAD

**Issue by skid42** [te-online/timemanager#173]
Hi,
I have created a few projects and wanted to share these with my employees. The are all in the group "employees", which is assigned through Active Directory. 
If I share the timemanager-client with the AD-Group: The users do not see the client.

As a test case, I created a Nextcloud group "NC-employees" and assigned users to this group. 
If I share the group NC-employees, the group-members can see the client.

Can anybody confirm this behaviour (it might be a configuration issue on my specific Nextcloud-instance).

Best 
Jochen

**Comment by te-online** [comment]
The app is using the `apps/files_sharing/api/v1/sharees` endpoint to search for users and groups. The `shareWith` property of the group is then used as the group id. Can you confirm that your AD groups show up with a usable `shareWith` property (maybe check your Network tab in the web developer console in your browser when searching for sharees)?

The being said, I think the most likely issue is that for looking up which users belong to which group, the app uses the `group_user` table in Nextcloud. Does this table hold a cache of AD groups for your Nextcloud instance?

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
