### ISSUE TITLE
Allow new tasks/projects in shared clients (by shared users)

### ISSUE THREAD

**Issue by skid42** [te-online/timemanager#174]
Hi,
I am managing the invoices for our company and need to see the hours for each client. 
I have created the clients and shared these with the employees. 

Setting up projects (and tasks) per each employee is a lot of admin-work. 
Would it be possible to let "shared members" create their own tasks (and ideally projects) inside a shared client?

**envisioned Structure:**
client (set up by me and shared with employee: I can see all hours, employee can see their own hours)
  project (set up by me / ideally by sharee)
     task (each employee creates their tasks as needed

 (This is different from "let shares be administrated by sharee" (https://github.com/te-online/timemanager/issues/78), as it's only allowing the creation of subitems without a specific user rights management).

Best Regard
Jochen

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
