### ISSUE TITLE
Allow switching between entering time in hour-format as well as decimal-format

### ISSUE THREAD

**Issue by te-online** [te-online/timemanager#18]
I'd like to introduce a time editor that can be configured to allow two types of input:
- Hour-format entries like this `01:30:00` for `1.5 hrs.` in the format `hh:mm:ss`
- Decimal entries like `1.5` for `1.5 hrs.` in the format `hh.1/6h`

see https://github.com/te-online/timemanager/issues/9#issuecomment-709927501

**Comment by joleaf** [comment]
Related to this, it should be also possible to switch between the duration format (1h) or a from-to timestamp format. (see android app)

**Comment by Ogolar** [comment]
> Related to this, it should be also possible to switch between the duration format (1h) or a from-to timestamp format. (see android app)

+1
In my Opinion very importened; without this option in the App it would not be useable for me

**Comment by dbfischer** [comment]
+1
I don't want to calculate what e.g. 17 minutes are in hour with decimal format.

**Comment by punkyard** [comment]
hi
for most people around me, it does not make sens to express time in half hours or 0.7 hours - but in minutes. 
could you give the option to express in minutes when adding a task? thanks

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏

**Comment by punkyard** [comment]
a couple of months have past, is it possible to request again a switch to minutes as it is a natural and easy way to express lengths of time

**Comment by foss-** [comment]
Fantastic news. Updated to 0.3.20 and changed the setting to `Input hours and minutes (02:30 hrs.)`.

Entering 00:10 for a 10 minute entry behaves as follows:

https://github.com/user-attachments/assets/cad8ffe1-9903-4227-b6f6-188cc214da11

**Comment by foss-** [comment]
Looking good, thanks so much 🙌
