### ISSUE TITLE
[Feature request] Add a month overview

### ISSUE THREAD

**Issue by EmJotGeh** [te-online/timemanager#19]
Thanks for this really useable Nextcloud App. Maybe there is a chance to implement a month overview feature?

**Comment by te-online** [comment]
Thanks for your suggestion 😊 
I can let you know that "reporting" is definitely on my radar as a broder feature. And that would most likely cover your request. But it will like take some time, I'm afraid. Anything you can do to help (detailed feature description, screen scribbles, UI design, implementation in JavaScript or PHP) is very welcome! :-)

**Comment by szekelyisz** [comment]
Yes please! Virtually the only feature missing from this app for me is the ability to filter time entries by time interval and client so at the end of the month I know how much I should bill my clients. I guess it needs two date entries to specify the interval, and three dropdowns for client, project and task. All three can be empty to match all, or selected to filter by the respective client, project and task. I think this arrangement will provide maximum flexibility to users. Hope that helps, I'm not a web wizard so better not touch the code.

**Comment by te-online** [comment]
@szekelyisz I agree. I was thinking about a reporting feature that would do exactly what you ask for. Cannot make any promises on when this will be coming, but I'll keep this issue open, since it's an interesting feature that someone might pick up at some point :-)

**Comment by te-online** [comment]
Please check out [version 0.2.0](https://github.com/te-online/timemanager/releases/tag/v0.2.0) for a reporting feature that addresses this feature request ✨
