### ISSUE TITLE
Cannot select a project when creating time entries

### ISSUE THREAD

**Issue by MexHigh** [te-online/timemanager#195]
I just installed the App to try it out, since the Time Tracker plugin (https://apps.nextcloud.com/apps/timetracker) is simply no fun to use. I wanted to add a test customer and project and add some times to it. However, the project picker doesn't let me select anything. The search works fine, but i cannot select anything and the input field stays empty.

I tried now for several minutes by using the arrow keys and resized the window, etc but nothing worked. Any ideas?

 
![image](https://github.com/user-attachments/assets/df170a90-76d2-4bd0-b32c-e2686a6e228d)

---

I'm using latest Google Chrome on Windows 10, and version 0.3.16 of TimeManager from the Nextcloud app store. Nextcloud version is 30.0.1.

Please let me know if I can give you more info on that issue!

**Comment by MexHigh** [comment]
Ok i figured it out. You can only select a task (I had none). Is this by design that you can only add time to a task and not a project itself? Doing adminstrative work for a project does not exactly match a specific task.
The input field also states "Customer, Project OR Task", however, I can only select a task.

**Comment by te-online** [comment]
Glad you figure it out 😊 

And yes, it's a huge usability issue! I'm going to close this in favor of #89
