### ISSUE TITLE
add screenshot to docs

### ISSUE THREAD

**Issue by Matthias84** [te-online/timemanager#2]
Hi, I guess most users like to see a screenshot, before they decide to test the app? This allows them to quickly see, if they get the idea of the app and if the UI will fit their needs.

**Comment by te-online** [comment]
Hey @Matthias84 thanks for your feedback! 🙂
Screenshots can be seen on the listing on the appstore where many users browse and install apps. (But you can actually find them in this repository as well - go to the img folder).
