### ISSUE TITLE
Mobile Android App

### ISSUE THREAD

**Issue by joleaf** [te-online/timemanager#24]
Hi @te-online ,

I just developed a mobile app for your NC Timemanager.
The first open beta version is available in the google play store [here](https://play.google.com/store/apps/details?id=de.jbservices.nc_timemanager_app).
Feel free to take a look at it :)
Also, the source code is open source and available [here](https://gitlab.com/joleaf/nc-timemanager-mobile-app).

The next version contains charts and a time tracking feature and will be released next week :) 

Maybe, if the app is in production, you can add a link to this app on the NC App site [here](https://apps.nextcloud.com/apps/timemanager)?

Best,
Jonas

**Comment by te-online** [comment]
Jonas, this sounds amazing 🎉🥳
Allow me a little more time to take a look at your app and to prepare adding the link to the app's description.
Would you mind updating this issue if you've released a stable version of your app?

**Comment by joleaf** [comment]
Today, I published version [21.2.0](https://play.google.com/store/apps/details?id=de.jbservices.nc_timemanager_app) as beta release. If there are no problems, it will be transferred to production next week. Any [feedback](https://gitlab.com/joleaf/nc-timemanager-mobile-app/-/issues) is welcome.

**Comment by joleaf** [comment]
New version:
- Time entries overview screen with timespan filter (maybe more filter in the future)
- Bugfixes

**Comment by joleaf** [comment]
@Thovi98 One friendly question? Can you help me translate the app into French? :)

**Comment by Thovi98** [comment]
Yes, of course I will ! Sorry that I didn’t propose you yet. 
I will try soon.

Did you know that as a Nextcloud app, you could integrate your app into the Nextcloud Transifex, so everybody could easily help translating into every language ? :) 
For more information, I’ve seen it here : https://github.com/vauvenal5/yaga/issues/24#issuecomment-751828442

**Comment by joleaf** [comment]
> Did you know that as a Nextcloud app, you could integrate your app into the Nextcloud Transifex, so everybody could easily help translating into every language ? :)
> For more information, I’ve seen it here : [vauvenal5/yaga#24 (comment)](https://github.com/vauvenal5/yaga/issues/24#issuecomment-751828442)

Yes, I know, but gitlab is not integrated right now :) I have a similar issue with the nextcloud password ap :) see https://gitlab.com/joleaf/nc-passwords-app/-/issues/6. and https://github.com/nextcloud/docker-ci/issues/248

**Comment by joleaf** [comment]
It may help if some of the users of the android app can write a short app store review.
Thank you :)

https://play.google.com/store/apps/details?id=de.jbservices.nc_timemanager_app

**Comment by te-online** [comment]
I'm going to close this for now, since no action is needed.
The issue will still be pinned to the issues page for everyone to see and hopefully discover the Android app :-)

**Comment by te-online** [comment]
@joleaf Hey – I know you don't have much time 🙂 But if you have a minute, I'm going to release a new version today that contains a major rewrite of the database mappers to restore compatibility with NC 26. 

I'd be curious to hear if the app still works as expected. 

I caught quite a few bugs after the rewrite by means of my existing end-to-end tests, but I don't use the app, so can't really test on that end 😬 

My idea is to release the new version today to not keep people waiting. But if you can see any issues with the app, I can push out another fix quickly.

**Comment by joleaf** [comment]
Hey @te-online , the problem is that I do not use this app anymore 😂
