### ISSUE TITLE
Undefined property: OCA\TimeManager\Db\Client::$hours at /srv/nextcloud/www/apps/timemanager/templates/projects.php#92

### ISSUE THREAD

**Issue by LeonGaultier** [te-online/timemanager#27]
Hallo,

Ich habe die App installiert und dann über die Android APP Kunden und Projekte erstellt. Dummerweise hat die Android App immer wieder ein und den selben Kunden neu angelegt pro Aktualisierung. In der Android App war nur ein Kunde zu sehen. Nun habe ich den einen Kunden in der Android App gelöscht. Aber ich habe noch 15 mal ein und den selben Kunden in der NC App. Kann die auch nicht löschen da ich folgende Fehlermeldung bekomme.

`Error: Undefined property: OCA\TimeManager\Db\Client::$hours at /srv/nextcloud/www/apps/timemanager/templates/projects.php#92
/srv/nextcloud/www/apps/timemanager/templates/projects.php - line 92:

OC\Log\ErrorHandler::onError()

/srv/nextcloud/www/lib/private/Template/Base.php - line 178:

include("/srv/nextcl ... p")

/srv/nextcloud/www/lib/private/Template/Base.php - line 150:

OC\Template\Base->load()

/srv/nextcloud/www/lib/private/legacy/OC_Template.php - line 180:

OC\Template\Base->fetchPage()

/srv/nextcloud/www/lib/public/AppFramework/Http/TemplateResponse.php - line 210:

OC_Template->fetchPage()

/srv/nextcloud/www/lib/private/AppFramework/Http/Dispatcher.php - line 123:

OCP\AppFramework\Http\TemplateResponse->render()

/srv/nextcloud/www/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch()

/srv/nextcloud/www/lib/private/Route/Router.php - line 309:

OC\AppFramework\App::main()

/srv/nextcloud/www/lib/base.php - line 1008:

OC\Route\Router->match()

/srv/nextcloud/www/index.php - line 37:

OC::handleRequest()`

Grüße

**Comment by te-online** [comment]
Hallo! Das ist merkwürdig und ärgerlich – und es ist sicherlich die Mühe Wert, ein Issue im [Repository der Android App](https://gitlab.com/joleaf/nc-timemanager-mobile-app) zu eröffnen.

Was genau hier das Problem ist, kann ich so aus der Ferne leider nicht sagen. Der Fehler, den du erhältst, rührt vermutlich daher, dass du ein Projekt hast, das keinen entsprechenden Kunden mehr hat. Daher können die Stunden nicht berechnet werden. Du hast also leider jetzt inkonsistente Daten.

Hast du Zugang zu deiner Datenbank? *Denke an ein Backup!* 
- Vielleicht kannst du den doppelten Kunden in der entsprechenden Tabelle finden und einen genauen Blick auf die Zeilen werfen? 
- Vielleicht kannst du das Projekt finden, das keinen Kunden mehr hat und dieses Löschen?

**Comment by LeonGaultier** [comment]
Hallo Thomas,

Ja Zugang habe ich, ist eine private Installation. Backup ist auch vorhanden. Also alles kein Problem. Ich versuche mal mir die Datenbank an zu schauen und Infos zum Aufbau zu bekommen. Danke Dir erstmal für die Antwort.

**Comment by LeonGaultier** [comment]
Hallo Thomas,

Ich habe es hinbekommen. Nun läuft es wieder. Alles andere werde ich bei Gelegenheit beim Android App Entwickler melden.


Grüße

**Comment by te-online** [comment]
Das freut mich zu hören 👍 Re-open gerne, wenn du einen Weg hast, das Problem zu reproduzieren, dann lässt es sich fixen 😊

**Comment by joleaf** [comment]
Hi @LeonGaultier und @te-online 

Das Problem hatte ich auch schon einmal während der Entwicklung der Android App.
Ich konnte das aber nicht nochmal nachstellen. Also falls das Schritt für Schritt nachgestellt werden kann wäre das super. Gerne dann ein Issue hier öffnen:
https://gitlab.com/joleaf/nc-timemanager-mobile-app/-/issues
