### ISSUE TITLE
[feature request] Add an optional start and end time

### ISSUE THREAD

**Issue by marun76** [te-online/timemanager#28]
Thank you for the great nextcloud app and the great Android app.

For me it would be very helpful if you could add a start and end time for each time entry additionally to the existing hours. My clients always want to not only have the date and amount of hours, but also the timeslot that the work was actually done (e.g. some working hours have a different fee rate than others, i.e. higher fees during nighttime etc). Therefore it would be great to hava a possibility to also enter time ranges like from "10:00" to "18:00" o'clock.

Also it would be very nice, if there was an opportunity to have a second and third hours field for unpaid breaks and for travel time, so you don't have to split these hours apart by entering them into three different tasks and/or projects.

Best regards

Manuel

**Comment by te-online** [comment]
@marun76 Thanks for your feature request.

Technically, each time entry has a start and enddate. I don't develop the Android app, but I believe you might be able to edit the dates there? Not sure.

But you're right that Nextcloud app UI doesn't expose the start/end times. It would be a nice improvement, but I don't need it myself and have to disappoint you in that I don't have any plans to add it to the UI. 

Pull requests are of course welcome, if you decide to work on a feature like this, open the PR as a first thing, so we can keep discussing the feature and how to integrate it into the app 😊 

> Also it would be very nice, if there was an opportunity to have a second and third hours field for unpaid breaks and for travel time, so you don't have to split these hours apart by entering them into three different tasks and/or projects.

Not sure I understand this feature, though 🤔 Maybe a "type" for the time entry could be a feature to solve this?

**Comment by joleaf** [comment]
I the android app you can switch between Start-End and a duration-based input format.
However, you have to set this option in a global scope.

**Comment by smatthie** [comment]
I support this feature request very much.

If start/end is already implemented in the database and it's just a matter of exposing them in the UI, can I ask you to reconsider and implement it?

In fact, the lack of start/end date is actually the reason why this app is unfortunately not usable for my situation, although I like practically everything else. But for me the key feature of time tracking is to record when I start and end a task; if I have to enter a duration at the end it means I still have to keep a note of the start time by some other means and then calculate the duration manually, which defeats the purpose of time tracking...

There's a similar app Timetracker (https://github.com/mtierltd/timetracker) which does this, but unfortunately it has many other problems and development seems to have stalled, so I was looking for a replacement, and timemanager looked almost perfect.

**Comment by te-online** [comment]
A basic version of this should be available in version 0.3.5
