### ISSUE TITLE
NC19 + Postgres: function lower(timestamp without time zone) does not exist

### ISSUE THREAD

**Issue by iwilltry42** [te-online/timemanager#3]
Hi, 
I'm running TimeManager on Nextcloud 19 with a Postgres Database.
I just installed TimeManager and when I try to access it, I hit the following error:
```
"message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_timemanager_time\" WHERE \"user_id\" = ? AND \"status\" != ?ORDER BY LOWER(\"start\") DESC;' with params [\"<username>\", \"deleted\"]:\n\nSQLSTATE[42883]: Undefined function: 7 ERROR:  function lower(timestamp without time zone) does not exist\nLINE 1: ...\" WHERE \"user_id\" = $1 AND \"status\" != $2ORDER BY LOWER(\"sta...\n                                                             ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts."
```
Any clue how I could fix this?

**Comment by te-online** [comment]
@iwilltry42 Thanks for reporting this – I'm sorry your experiencing this issue.
I'm in no way expert in Postgres, but I assume that it doesn't like the timestamp in this query. Let me look into this a bit and I'll report back here.

**Comment by te-online** [comment]
@iwilltry42 Hey again, I made a quick bugfix that – so I believe – addresses this issue. However, I don't have a Postgres install handy. Would you mind replacing the `db/objectmapper.php` file with [this fixed-up version](https://github.com/te-online/timemanager/blob/bugfix/issue-3/db/objectmapper.php) on a non-production install at your disposal?

**Comment by iwilltry42** [comment]
Hi @te-online thanks for the quick response :)
I can confirm that the fixed up version of `db/objectmapper.php` does the trick and now everything works as expected :+1: 
By the way: In Nextcloud's dark mode (Breeze Dark), the text highlighting and color is a bit off and hard to almost impossible to read.

**Comment by te-online** [comment]
@iwilltry42 Perfect, thanks for testing. I'll prepare a new release soon. I've never used dark mode, but will make sure to test and fix it 😅

**Comment by iwilltry42** [comment]
I also just found out about the dark theme 😁
Thanks for your work on this 👍
