### ISSUE TITLE
[Feature Request] Sync with time Tracker

### ISSUE THREAD

**Issue by Gunnar-GO** [te-online/timemanager#30]
[Time Tracker](https://github.com/mtierltd/timetracker/) has the similar scope but offers other solutions.
Is there a way to sync up the both apps?

**Comment by te-online** [comment]
Hey @Gunnar-GO – I'm not sure I understand your feature request 😅 You would like to sync data between the apps? I'm not very familiar with Timetracker, so I don't know what API they expose and if the data schemas would even be compatible. 

This issue looks similar to your request, please note my longer response there 🙂 #22 

I'm sorry I can't help that much with this particular feature request. However, know that whenever you'd like to help improving something else about this app, you're more than welcome to contribute with ideas, code, sketches or another issue.
