### ISSUE TITLE
NC 22 compatibility

### ISSUE THREAD

**Issue by jpkop** [te-online/timemanager#34]
Hi!

Could someone test if the app is compatible to NC22? I would not want to miss this one.

Thank you.

**Comment by te-online** [comment]
Sure, I'm not exactly an early-adopter with new NC versions, so it might take a while more, but it will land eventually.

**Comment by joleaf** [comment]
After upgrading to NC 22 the TimeManager app isn't working anymore:
"The appinfo/database.xml file is not longer supported. Used in timemanager"

**Comment by te-online** [comment]
Thanks for checking. I didn't expect `database.xml` to be deprecated so soon 😢 
Will have to get that fixed for NC 22 compatibility. I created an issue and will get back to it as soon as I can: https://github.com/te-online/timemanager/issues/36

**Comment by thoash** [comment]
Hi, when can we expect NC22 support?

**Comment by te-online** [comment]
Fixed in [0.2.3](https://github.com/te-online/timemanager/releases/tag/v0.2.3)
