### ISSUE TITLE
Time manager dashboard doesn't show statistics for Sunday

### ISSUE THREAD

**Issue by purple-teaboy** [te-online/timemanager#35]
Good morning all, and many thanks for this app.

I've spotted some weird behaviour in the Statistics display on the Dashboard.

I've just added two hours to a task today (Sunday), but the Statistics section of the Dashboard claims that I've logged no hours today. Similarly, the count for the week is only the two other entries that I have. It's not that the last entry is missed, as the last entry (on the same project) was the Saturday one shown in this screenshot.

![Screenshot from 2021-07-11 10-44-00](https://user-images.githubusercontent.com/73671705/125190437-06ca5700-e235-11eb-94a4-76f19e628227.png)

Going back and forward in the weeks, there is no entry on any Sundays, even though I added one to the week before (4th July) just in case it was picking that up (it wasn't). Moving back to the current week still only shows the two hours.

Then I realised that there was a "current week" button if you aren't on the current week. And, after clicking that, the missing time appears:

![Screenshot from 2021-07-11 10-52-47](https://user-images.githubusercontent.com/73671705/125190677-34fc6680-e236-11eb-891e-4979cfa4507e.png)

I looked, and there are now bars for the Sundays with tasks, if you go back and forward by week. However, as soon as you navigate away, and then click the Dashboard link in the top left corner, the Sunday bars vanish, and the week totals adjust to match.

Browser is Vivaldi, running on Debian Linux, if that makes a difference. I can try on other platforms and browsers if required.

**Comment by te-online** [comment]
That sounds like a bug you found 🐛 
I will try and reproduce & fix it as soon as I find some time 😊
