### ISSUE TITLE
[Feature request] Working day specifications: break time, travel time, type of vehicle

### ISSUE THREAD

**Issue by MiMoHo** [te-online/timemanager#45]
Add options to specify the break times (lunch and 2nd break), travel time to location and return and type of vehicle (car, truck) used for the journey each day in addition of issue #28 so that an employee-friendly time sheet can be exported that one can sign manually or digitally by pasting a (.png) signature image.

**Comment by te-online** [comment]
Hi @MiMoHo Good to see your many ideas, there's a lot! 😅

>  specify the break times (lunch and 2nd break)

I'm not sure I understand this one. How would break times affect your time tracking? Wouldn't you stop your timer during your break? Or subtract them when noting down hours at the end of the day?

> travel time to location and return and type of vehicle (car, truck) used for the journey

You might be able to "hack" around this by using a dedicated project/client on each client/project to track traveling, using the notes field to store information about your trip and vehicle used. There are no plans, however, to add a feature around travel tracking.

> so that an employee-friendly time sheet can be exported that one can sign manually or digitally by pasting a (.png) signature image 

Can you elaborate on that one as well? 🙂 I have a vague idea that you'd want to have sort of an export that an employee can sign to express it being correct?

**Comment by benjamindahl** [comment]
+1

**Comment by MrLoverLoverMMMM** [comment]
+1

**Comment by MrLoverLoverMMMM** [comment]
+1

**Comment by GVLLIFESTYLE** [comment]
+1

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
