### ISSUE TITLE
Report printout looks different

### ISSUE THREAD

**Issue by ikonnow** [te-online/timemanager#47]
https://github.com/te-online/timemanager/pull/29#issue-657092952
When I tested TimeManager in order to evaluate to what extent this tool can already be used in production, I noticed that: after entering a time and trying to create a print file from the report with the diagram view, the bars symbolizing the time entry are not filled, but displayed as outlined.

A direct link from the dashboard to the report would be ideal to create a report directly from the current / selected week.

**Comment by te-online** [comment]
Yeah, I'm not exactly an expert in print stylesheets (because nobody ever uses or teaches them – we should!).
But I believe you can fix this particular issue, by selecting "Print background" in your browser's print dialog.

**Comment by te-online** [comment]
I'm going to close this, because I'm assuming that this trick fixed the issue for you 🙂
