### ISSUE TITLE
Bug: Update Time Entry is not working

### ISSUE THREAD

**Issue by joleaf** [te-online/timemanager#48]
Hi, I just tried to update a time entry. Unfortunately, I was not able to do so (See clip).
![image](https://user-images.githubusercontent.com/71190322/133246124-1af2f4f7-c424-4425-98f5-7717159f1987.png)

The JS Console printed the following: 
PATCH https://......de/apps/timemanager/times?task=43088a65-d695-429a-b013-74c229a5fb07 500 (Internal Server Error)

**Comment by te-online** [comment]
Hey @joleaf, thanks for reporting. Can you check your `nextcloud.log` to see what's causing this `500`?

**Comment by joleaf** [comment]
Here is the error from the log:

Error    index              Exception: in_array(): Argument #2 ($haystack) must be of type array, string given at                                    2021-09-16T09:05:12+00:00
                              lib/private/AppFramework/Http/Dispatcher.php line 158

                              0. lib/private/AppFramework/App.php line 156
                                 OC\AppFramework\Http\Dispatcher->dispatch(OCA\TimeManager\Controller\PageController {}, "editTime")
                              1. lib/private/Route/Router.php line 301
                                 OC\AppFramework\App::main(
                                   "OCA\\Timemanager\\Controller\\PageController",
                                   "editTime",
                                   OC\AppFramework\DependencyInjection\DIContainer {},
                                   {_route:"timemanager.page.editTime"}
                                 )
                              2. lib/base.php line 1000
                                 OC\Route\Router->match("\/apps\/timemanager\/times")
                              3. index.php line 36
                                 OC::handleRequest(

                                 )

                              Caused by TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given at
                              custom_apps/timemanager/db/storagehelper.php line 66

                              0. custom_apps/timemanager/db/storagehelper.php line 66
                                 in_array(
                                   ["d0932b63-cdb1-4265-9db5-a36e4db9cf15","c5c6379f-a36d-4024-a135-1668697956bc","6eccb0e2-dec9-453d ... "],
                                   "ae51cc96-2d39-4133-9855-5553aec1d7bd"
                                 )
                              1. .../timemanager/controller/pagecontroller.php line 846
                                 OCA\TimeManager\Db\StorageHelper->addOrUpdateObject(
                                   {uuid:"68e94442-a43d-4e48-a232-5f165c2a9d01",start:"202 ... "},
                                   "times"
                                 )
                              2. lib/private/AppFramework/Http/Dispatcher.php line 217
                                 OCA\TimeManager\Controller\PageController->editTime(
                                   "68e94442-a43d-4e48-a232-5f165c2a9d01",
                                   4,
                                   "2021-09-14",
                                   "xxxx"
                                 )
                              3. lib/private/AppFramework/Http/Dispatcher.php line 126
                                 OC\AppFramework\Http\Dispatcher->executeController(OCA\TimeManager\Controller\PageController {}, "editTime")
                              4. lib/private/AppFramework/App.php line 156
                                 OC\AppFramework\Http\Dispatcher->dispatch(OCA\TimeManager\Controller\PageController {}, "editTime")
                              5. lib/private/Route/Router.php line 301
                                 OC\AppFramework\App::main(
                                   "OCA\\Timemanager\\Controller\\PageController",
                                   "editTime",
                                   OC\AppFramework\DependencyInjection\DIContainer {},
                                   {_route:"timemanager.page.editTime"}
                                 )
                              6. lib/base.php line 1000
                                 OC\Route\Router->match("\/apps\/timemanager\/times")
                              7. index.php line 36
                                 OC::handleRequest(

                                 )

**Comment by te-online** [comment]
Yeah, I can see from the code in this file, that the attributes of `in_array` seem to be switched. 

Maybe your setup is more strict than mine, because for me it works regardless 🤷‍♂️ 

Of course this is something we should get fixed, by switching the arguments of the `in_array` call or evaluating if this part of the code is even necessary if it was broken all this time ...

**Comment by te-online** [comment]
@joleaf Could you check if it works again using the latest release?

**Comment by joleaf** [comment]
It's working now. Thank you!!
