### ISSUE TITLE
[Feature Request] Assign default client

### ISSUE THREAD

**Issue by t3k4y** [te-online/timemanager#49]
Thank you for this very useful nc-app!

It would come very handy if one could configure a client as default that is pre-chosen in the new-entry-form.  For example in case the focus lies on one client at the moment.

Best regards,
tk.

**Comment by te-online** [comment]
This sounds like a nice idea. I was thinking about adding some useful UX improvements to the "Quick Add" form, like pre-selecting the last client/project or something like that. 

Will keep this issue updated, when it comes to this. If anyone else would like to work on this, everyone is very welcome 🙏

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
