### ISSUE TITLE
Error displayed in logfile (NC 19): "failed to open stream"

### ISSUE THREAD

**Issue by guyfromouttaspace** [te-online/timemanager#5]
I installed on a stock Nextcloud setup (ver. 19) timemanager and noticed that there is a recurring error output in my log:

file_get_contents(/www/htdocs/xyz/xyzxyz.de/space/apps/timemanager/helper/../js/views/Statistics.svelte): failed to open stream: No such file or directory at /www/htdocs/xyz/xyzxyz.de/space/apps/timemanager/helper/php_svelte.php#9

It seems like a bug - also after entering some example data it continues to show up in the log. Thanks for help!

**Comment by te-online** [comment]
@guyfromouttaspace Thanks for reporting this issue :-) This should not affect any functionality. It cannot find a template for server-side-rendering that is only used on the client-side right now. Server-side-redering is a fallback for when the JavaScript breaks, but as I wrote, this specific template (Statistics) is only in use in the client-side bundle. While the logs might be annoying, it shouldn't do any harm. Taking a look at the file include part that's causing this, it probably needs to be rewritten to make it more robust and secure.
