### ISSUE TITLE
[Feature Request] Add an hourly rate per Client

### ISSUE THREAD

**Issue by stijink** [te-online/timemanager#51]
Hi,

first of all thanks for your work. A very handy tool :-)

Now for the feature request. It would be nice to have the possibility to add an hourly (payment) rate per client. This rate could then be used to sum up income in the Reports section.

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
