### ISSUE TITLE
Another oddity in the Statistics pane of the dashboard

### ISSUE THREAD

**Issue by purple-teaboy** [te-online/timemanager#52]
Another silly bug from me, I'm afraid.
![image](https://user-images.githubusercontent.com/73671705/137140339-e2a89e06-3eb7-4738-95ee-9aaa2795df67.png)

Looks like there's a rounding issue when the time is displayed. An export of this week's entries is attached as [report_2021-10-11_2021-10-31.csv](https://github.com/te-online/timemanager/files/7338429/report_2021-10-11_2021-10-31.csv)

I'm wondering if it is being skewed as I'm using the Android app to create some entries (with actual start and end times) and the web version for others.

**Comment by te-online** [comment]
Nice catch, I'll get the output of that fixed soon 🙌

**Comment by te-online** [comment]
This should be fixed in 0.2.6
