### ISSUE TITLE
Feature request: Add an optional "timer" for counting down, instead of just using a "stopwatch" that counts up

### ISSUE THREAD

**Issue by mstyp** [te-online/timemanager#55]
Currently the the app tracks your timeusing a "stopwatch", that is to say, it starts at zero and counts up.

I would like it if there was an option to instead *count down* with a "timer". that is to say, at the beginning you set the amount of time you would like the timer to run, then when it hits zero it plays an alarm and stops tracking your time

Naturally you should be able to stop tracking if you finish a task early, or extend the task if you need more time, but for me I see a timer counting down and an alarm at the end to remind me to either move on to the next task or stay on target to be much better for my productivity then a stopwatch that does nothing but count up.

**Comment by te-online** [comment]
Hey @mstyp – thanks for sending in a feature request. I believe you're better off opening that request on the actual mobile app's repository as I'm assuming you're referring to a feature in the Android app: https://gitlab.com/joleaf/nc-timemanager-mobile-app

**Comment by mstyp** [comment]
no, actually, I've been unable to get the android app working. this is a feature request for the nextcloud app to track time via a timer and not via a stopwatch. 

Ideally it would also be a Pomodoro timer of some sort but that's actually not necessary for my particular workflow.

**Comment by te-online** [comment]
@mstyp Have you tried the latest version of TimeManager with the Android app? There were some connectivity issues.

I'm not really sure I understand all the terms your using. What's the difference between a timer and a stopwatch in the context of time tracking? I don't think that TimeManager has either of those right now. And can you elaborate a bit on what a Pomodoro timer is and how it would work in this context? Now I'm curious 😉 🍅

**Comment by mstyp** [comment]
thats fair, a timer *counts down*, and starts yelling at you / making noises when it reaches zero. A stopwatch *counts up*, forever, untill you tell it to stop. When you are using a stopwatch, you are saying "I want to keep track of how long, exactly, this task takes me" (informative, and useful if you bill by the hour or whatever). When you use a timer, you are saying "I think this task will take x ammound of time, and so I am going to finish it before the timer hits zero" (just as informative, because you are still tracking how long it took you to do the thing, but also more motivating, at least for me)

Currently the application is a stop watch, you start it, it starts recording your time, then just keeps going. What I am asking for is that, instead of clicking the start button and seeing your time increment up, the user has an option to switch over to a timer counting down. when timer hits zero, an alarm clock should play sound, time tracking should stop. of course, behind the scenes its still tracking how much time passed and adding that to your time tracking, but now the user has the option to limit the bounds of the tracker, and has a way to be notified when they are starting to go over their alloted time. 

I budget /track my time pretty severely, and use a lot of timers to make sure I stay on task. so, like, when I wake up, I automatically start a 45 minute timer, and thats how long i have for waking up and eating breakfest and so on. f I dont have a timer reminding me to stay on task, Itend to get pulled to deep into whatever it is Iam working on and forget to move on to the next thing. 

Pomodoro is just a workflow that uses short timers + breaks. https://en.wikipedia.org/wiki/Pomodoro_Technique

**Comment by te-online** [comment]
Okay, cool, thanks for your thorough explanation 👍 🤗 
I had actually heard of Pomodoro technique before, but forgot all about it 😅 

However, I'm still a bit confused, because TimeManager doesn't include a stop watch feature. You can only _retrospectively_ insert time entries 🙂 Maybe you've tried the other Nextcloud app that has such a feature. 

Regardless, at some point a [stopwatch feature will be added](https://github.com/te-online/timemanager/issues/11) since it has already been requested and I can look into it also having the option to switch to a timer mode.

As with all feature requests for features that I don't personally use, I have to give the disclaimer that there is no roadmap since I don't have a lot of resources to throw at this project. You are, however, more than welcome to contribute in any form to get this feature into the app.
