### ISSUE TITLE
Time Manager Reports are inaccurate when applying client / project filters and From / To Time range (via Preset)

### ISSUE THREAD

**Issue by kippistudio** [te-online/timemanager#58]
I'm trying to generate a Report for my working hours. Therefore I switch to the 'Reports' tab in the Nextcloud Timemanager and select the client and project in question (tasks and status left untouched / empty) and selecting Preset 'last month' and applying these settings.
In the 'Bar graph' from the generated report all days from (In this case 1.11.2021 to 30.11.2021) are shown correctly with entered time values. However, in the summary below (Report Total / Number of entries) the last day (30.11.2021) is not shown and / or summed up in the calculation, rendering the report inaccurate. This applies to a printout and cvs export as well.

**Comment by kippistudio** [comment]
TimeManager is version 0.2.6 and Nexcloud Version is 22.2.3 (stable)

**Comment by te-online** [comment]
Going to look into this, but can't promise a fix in the next release that is due very soon because of NC 23. Sounds like an annoying bug, I'll get it fixed 🙏

**Comment by te-online** [comment]
This should be fixed in 0.2.7 Beta 👍 Please re-open if you experience issues with this again 🙂
