### ISSUE TITLE
[Feature Request] Compatibility with Deck / Tasks apps.

### ISSUE THREAD

**Issue by phlegx** [te-online/timemanager#60]
Hi!

Please add possibility to associate tasks to a project from Deck app. [Nextcloud Deck](https://github.com/nextcloud/deck) is a kanban style organization tool aimed at personal planning and project organization for teams integrated with Nextcloud. Deck is developed by Nextcloud itself. I think it could be an important feature if users can choose and associate **Deck app tasks / boards**, [Tasks app](https://github.com/nextcloud/tasks/) tasks or TimeManager app tasks to a project for time tracking. 

See this issue on Deck app: nextcloud/deck/issues/2299
See proposal from a issue comment: [te-online/timemanager/issues/1#issuecomment-912702198](https://github.com/te-online/timemanager/issues/1#issuecomment-912702198)

**Comment by te-online** [comment]
Hey there 👋 Thanks for your suggestion! I can see how this could be useful, however, right now I can only refer to my de facto standard-answer to feature requests:

> I'm afraid I have to manage expectations here, as with many other features, and I hope you understand: This is not something that's on my personal roadmap right now. Unfortunately, if no help comes along, it has to wait. That's because it will require some major changes.

> Everyone is of course welcome to contribute by diving into the code and creating a PR.

> I'm sorry if this isn't the answer you were hoping for 😞

**Comment by mhanmore** [comment]
Not to repeat the same point too often, but I'm about 5 days in to setting up a nextcloud hub for time and diary tracking and already strongly agree that the option of pre-filling a time entry based on an existing Deck card would be really nice to have.  In practice I just end up creating shadow tasks in timekeeper, but in case it is easier to implement than full two-way integration it'd just be nice if those timekeeper shadow tasks could be created more quickly by e.g. pulling some info from Decks in an optional drop-down.

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏

**Comment by hublex** [comment]
Hi Mate, thx for the great work. What about giving away the code of you timemanager app and let others make a new, other app out of it where a connection between deck and calendar is possible?
Cheers

**Comment by te-online** [comment]
Hello @hublex 

I’m glad you like the app!

The code for the Nextcloud app is free and open source and can be browsed and forked right here on GitHub, you can click “Code” in the top navigation of this repository.

The code for the Android app is created by someone else, you can find the code over here https://gitlab.com/joleaf/nc-timemanager-mobile-app

I would advise you to go with the commercial solution, you’ve mentioned in another post, because it seems to better fit your needs.

Please understand that I do not have the resources to implement any kind of connection to other Nextcloud apps at this point, as I maintain my Nextcloud apps as a hobby in my free time.
