### ISSUE TITLE
update to 2.7 (beta)?

### ISSUE THREAD

**Issue by EmJotGeh** [te-online/timemanager#62]
I think there is a small issue on the Nextcloud Apps page. It seems, this prevent an update to version 2.7 and make this usefull app compatible for NC 23.

**Comment by te-online** [comment]
Thanks for raising this, I didn't notice. Did they lose some releases? 🤔 🤯

**Comment by te-online** [comment]
I think I got it uploaded again 🙏

**Comment by EmJotGeh** [comment]
No, everything is fine - I just noticed that version 2.7 beta has not arrived on my NC instance. Although on apps.nextcloud it is available. However, only version 2.6 is displayed. (Move on the Link, you will see that's version 2.7) I'll see if I can install the update on my instance. Many thanks

**Comment by te-online** [comment]
Good to hear 🙂 Well, I'm pretty sure the update was marked as latest on Dec 4th 21, but then it disappeared again from the appstore. Not sure why, but unfortunately the appstore is more than flaky at times...

**Comment by te-online** [comment]
My bad 🙈 Maybe one should update the version in info.xml as well... But it's always good to put the blame on the appstore 😉 

Could you try again? 🙏

**Comment by EmJotGeh** [comment]
Yes of course - no problem :-) It looks like this will work now! On apps.nextcloud is it already listed.

**Comment by EmJotGeh** [comment]
Ok, now it works! - Gut, und vielen Dank für die Klasse App :-)
