### ISSUE TITLE
Small suggestion/wish for improvement: time planning option

### ISSUE THREAD

**Issue by Django-BOfH** [te-online/timemanager#80]
The app is great for managing tasks and proving the time "spent" on them. 

What I personally miss, however, is a function or the possibility to record tasks in advance and to plan their completion. 

What do I mean by that? 
Well, let me illustrate it with an example. I have 40 hours per week available for tasks. That makes 160 hours for four weeks per month. So far clear, isn't it? If someone approaches me and asks me to take on a high-priority task, I estimate how much time I will need for it. Let's assume that I estimate 1 1/2 weeks for this, i.e. 60 hours, then I mentally note how much "remaining time" I still have available, in this example 100. At the moment I do all this on paper to keep track of everything that is pending, how much time I have planned and used for it and how much remaining time budget I have. Thus, it is easy to name realistic realization times, i.e. binding end dates, for further requests, because with a planned remaining budget of, let's say, 20 hours, it makes no sense to accept a task that would take 40 hours to complete and would have to be completed in the current month / time period. I also know what I have to do on the next working day and how much time I have planned for it - in short, this is called time planning. 

So now I've arrived at a time planning app, which basically still focuses on time management or time verification and less on the planning of times.

Could you imagine to extend the app by the important point of time planning? I would be happy to provide you with technical support, but unfortunately my skills and knowledge are not sufficient in terms of programming.

**Comment by te-online** [comment]
Hey @Django-BOfH Thanks for your feature request 👍 

I'm surprised you call it a small suggestion 😆 Looks more like a big new aspect _(or separate app?)_ for me. Project and time management are quite hard and while I might be able to add elements of it to the app eventually, unfortunately, I don't think TimeManager will become a good planning tool in the near future 😢 

A tool that I always liked is https://cushionapp.com/. It's a subscription-based closed-source solution outside of Nextcloud, though, so maybe not exactly what you're looking for 😉 

Will keep this open in case this feature will appeal to future contributors or users.

**Comment by Django-BOfH** [comment]
Well, it's just a little suggestion I had there. And since timemanger can do one thing well, why not extend it with the second (important function)? I guess a bottle of the best Irish whiskey wouldn't motivate you either, would it? 

Of course I confess, I can't estimate in any way how big the effort would be to realize something like this programmatically. That's why I naively tried to ask you as friendly as possible, if you could imagine to extend the TimeManager by the planning part. SO that not only the recording of already processed times and tasks but also the planning of tasks and their priorities and estimated time expenditures would be possible with it.

**Comment by Django-BOfH** [comment]
All is well, all is fine!

That was just a wish, a suggestion that I expressed.

And who knows, maybe you will be bored to death and you don't know how to waste your time senselessly, then you now have a possibility to change that ...

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
