### ISSUE TITLE
Adding time entries with keyboard 

### ISSUE THREAD

**Issue by pabloarias** [te-online/timemanager#82]
First, thank you very much for your work and this great software!

I'm having an issue with newer versions. When I add a time entry from Dashboard, I add a note, push tab, add duration, push tab, add a date, push tab, select client, push tab and select a task.

This worked fine until some time ago. Now, when I select a client, push tab and try to select a task, it selects the next client in list, not a task.

It's me or there is a bug?

Thank you and best regards

**Comment by te-online** [comment]
Hey @pabloarias Thanks for reporting this bug!

I've seen this before when using it myself – but for me it changed the selection of the client in sync with selection of a task, which is very annoying. I don't quite know what causes this bug, but probably something around focus. 

I'm preparing a rework of the quick-add section, though, which should fix this bug among other things. So stay tuned for updated to this area with improved UX 🙂

**Comment by te-online** [comment]
Please re-test this with 0.3.3 and re-open if the issue still exists 😊

**Comment by pabloarias** [comment]
Wow!!!

I've updated to version 0.3.3. This part has been improved a lot!!

Thank you very much!!
