### ISSUE TITLE
[feature] Full report from group member or all

### ISSUE THREAD

**Issue by vodihu** [te-online/timemanager#84]
Hello,
first of all this is a great alternative to Kimai for us, we work as a small team (3-4) and this kind of time tracking fast and simple is just right for us.

One wish we would like to have:
**It should be possible that not only the owner can create reports** (export csv, print) about all entries. Because admin and accounting are often different roles. 

Maybe a global flag to disable "[...]You can see all time entries, while others can only see and edit their own time entries." so that everyone can report.

And later maybe about groups, circles or users a more filigree setting.

That would be great! Thanks a lot!

**Comment by te-online** [comment]
Hey @vodihu 

Thanks for your feature request. I agree, more fine-grained sharing control would be really nice. 

I'm considering a first, more simple step as you suggest, but I also want to avoid just covering very specific use-cases... I'll keep you updated if anything moves in this area!

**Comment by joerggermany** [comment]
Hallo @te-online,

yes, an individual permission option would be a really good feature.

Thank you for your work on this app and best regards
Joerg

**Comment by te-online** [comment]
Your feature request is valid and I appreciate your input 😊 

However, in an effort to focus on maintaining existing features, I'm closing feature requests like this one for now.

For more context, please take a look at [the "Update strategy" section of the Readme](https://github.com/te-online/timemanager?tab=readme-ov-file#update-strategy) 🙏
