### ISSUE TITLE
Work input reload site when push key ENTER

### ISSUE THREAD

**Issue by UteHaus** [te-online/timemanager#85]
It would be nice if I could confirm my work input at the "Timer" page with the keyboard key ENTER.

On the following picture you can see the affected page and with the arrow the affected input field is marked.
After typing "What have you done?" it would not be bad if you could confirm the input with Enter instead of pressing the "play" button with the mouse on the right site.
  
![grafik](https://user-images.githubusercontent.com/31124997/187834548-1ceaeeb1-7567-4ed4-9e14-d1e7be99d659.png)

PS: amazing job! Keep going the good work! 👍

**Comment by te-online** [comment]
Hey @UteHaus Thanks for your kind words.

Can you tell me exactly, which form you can't submit using the Enter key? Would you mind sharing a screenshot or photo of your screen? Thanks! 🤓

**Comment by te-online** [comment]
Oh, I can see you updated the description with a photo! Sorry, I did not see this earlier...

Unfortunately, [the app you're using is located here](https://github.com/mtierltd/timetracker) and maintained by someone else. Hope you find help over there 😊
