### ISSUE TITLE
[Feature Wish] Recording of working time for legal documentation

### ISSUE THREAD

**Issue by t52lE4MWEcgCx** [te-online/timemanager#92]
Hi @te-online !

Maybe you know that: "Employers in Germany are obliged to introduce a system of recording working time."

I wonder whether TimeManager can be a tool to fulfil this obligation. 

IMHO, one could set one's own company as a client. Then a "Start workday" and "End workday" would be nice. Then breaks (like lunch) would be good to record (it's important to track that people had at least a 30 min break after 6h of work). Other breaks, like leaving for some personal business would be nice too. Later features could include issues like "I went to the doctor", or so. At to this a nice report at the end of the month to sign by both parties and then store it on NC. 

What do you think about this use case? Maybe it's already possible (or it will be shortly).

Thanks for reading this and best wishes,
Ralph

**Comment by te-online** [comment]
Hey @t52lE4MWEcgCx 👋 

Thanks for your question.

While you won't find a specific feature for this use-case, I think it is supported.

You can create a client named something you would identify as your company. Then you could create time entries just like you normally would, but only to track the time that you work – not on what specifically. You could just leave the description blank. 

At the end of each month, you can create a report just for this "client" and export this report to a CSV file (or print it to a PDF right from your browser). In your spreadsheet software, you can export as PDF or print to another digital file, then you can sign the document.

There is no tracking of specific constraints, like breaks or maximum work hours. I know they are mandated by law and I feel like they make sense in some professions, but I'm not sure I'd like to add a feature just for this requirement, sorry.

If _you_ would like to add some of this as a bonus feature (maybe an optional view mode), just make sure to open a PR before you get too far into it, so we have a place to discuss and where you can ask questions. I'm happy about every contribution 😊

**Comment by t52lE4MWEcgCx** [comment]
Thank you, @te-online, for your answer! 👋

I will start with the following setup: client - "Company", project - "Record work time", tasks - "work" and "break". For now, only I will play around with it. Calculating overtime would be helpful :-) 

First thing I noticed: I can only share a customer with a user, not a group. That would be helpful, I think. Maybe it would be helpful for projects and tasks too. 

I look forward to the start and end-time feature, you work on with devattendant. 

PR has to wait for now - and it might be a nice project for someone who hasn't coded for ages. 

Cheers,
Ralph

**Comment by beccon4** [comment]
> While you won't find a specific feature for this use-case, I think it is supported.
Apart for the fulfilling ludicrous labour regulation we have to comply with here in Germany - all the years I'm freelancing, at the end of each month accompanying the incoice I send a time sheet to the client containing the following:

```
+-day -----+- come-+-go-+lunch-+--time worked-+-topic --+
8.11.2022  10:00 - 20:00 break 2h -> 8h "Analyzed Nextcloud Time Tracker" 
9.11.2022  08:00 - 19:00 break 1h -> 10h "have fun at the home office with Nicole ää Nextcloud :-)"
```
So they can double check what I've done for them ans if I was present and I can see what I've done throughout the day which is especially useful when I work for multiple clients with the work times intertwined (such as right now when I doing analysis on Nextcloud which I do not want to charge the client for)

Extremely nice (and an advantage to the current spread sheet) would be just hitting a button at the mobile or in the Nextcloud for "come" and "go" to record the times. As the app is now it makes things more complex.

**Comment by te-online** [comment]
I'm wondering what we should do with this issue? It seems to be missing a concrete goal. I'm going to close for now, please re-open if anyone can come up with a more concise description of what I should add 😊
