### ISSUE TITLE
[Feature Request] Sharing with others

### ISSUE THREAD

**Issue by BB543** [te-online/timemanager#93]
As I understand it, customers/projects/tasks can currently only be used privately.
However, I would like to use this with my team so that everyone can book their time on the same project.
Do you have this on the agenda?

**Comment by te-online** [comment]
You can currently share customers/clients with other users in your Nextcloud instance. This will make all sub-projects and tasks available to them. They can also create time entries, but they won't be able to see or edit other's entries.

Would that solve your case for the time being?

**Comment by BB543** [comment]
Okay, I have discovered the option to share the client. Only unfortunately I can't share this to any group.

For our use, it would be important that everyone can create customers and projects and certain people have access to them to write invoices or to be able to control the working hours/workload.

Also it would be great if one can book/edit the times for others, because in our case also several people work on the same project. Currently it is enough if one person books the times.

**Comment by glenux** [comment]
Having more control over the sharing feature is really important, I think.

My use case is the following. As a director of my company, I need to:

* **share clients** (and all their projects) either with single users or with user groups,
* **share specific projects** either with single users or with user groups,
* **be able to assign specific permissions** to some users/groups as part of that sharing 
  * ex: allow my project managers to reorder/edit time entries
  * ex: give a read-only access to my administrative assistant (who does the invoices)

@BB543 : Is this what you had in mind?

**Comment by BB543** [comment]
@glenux - exact!
