### ISSUE TITLE
Change task for saved time entry

### ISSUE THREAD

**Issue by AlterDepp** [te-online/timemanager#95]
Is it possible to change the task for a saved time entry?
Stefan

**Comment by te-online** [comment]
Hi Stefan 🙂 

If you want to edit the parent task: Yes! You can navigate to the screen of the task that lists all the time entries. Then click on "Edit" to edit the task name. 

If you want to move a time entry to another task, unfortunately that's not possible. But #61 requests the same feature.

Hope this helps a bit 😊

**Comment by AlterDepp** [comment]
Thanks, #61 is, what I want. Sorry I didn't find this issue.
